# Etap 1:
FROM golang:alpine AS builder

ARG VERSION=1.0.0
WORKDIR /app
COPY main.go .
RUN apk add --no-cache git && \
    go build -o webapp -ldflags="-X 'main.Version=${VERSION}'" main.go

# Etap 2: 
FROM nginx:alpine

COPY --from=builder /app/webapp /usr/local/bin/

RUN rm /etc/nginx/conf.d/default.conf && \
    echo -e 'server {\n\
    listen 80;\n\
    location / {\n\
        proxy_pass http://localhost:8080;\n\
    }\n\
}' > /etc/nginx/conf.d/app.conf

RUN echo -e '#!/bin/sh\n\
/usr/local/bin/webapp &\n\
exec nginx -g "daemon off;"' > /start.sh && \
    chmod +x /start.sh && \
    apk add --no-cache curl

HEALTHCHECK --interval=30s --timeout=3s \
    CMD curl -f http://localhost/ || exit 1

EXPOSE 80
CMD ["/bin/sh", "/start.sh"]